// packages/client/blog-front/src/routes/login/+page.svelte

<script>
    let login = 'Hoar';
    let password = 'Hoar123';
  
    /**
     * @param {{ preventDefault: () => void; }} event
     */
    async function handleSubmit(event) {
      event.preventDefault();
  
      const formData = {
        login: login,
        password: password,
      };
  
      const response = await fetch('http://127.0.0.1:8000/api/user/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
  
      const data = await response.json();
      console.log(data);
    }
  </script>


<div class="flex flex-col justify-center items-center bg-[#fff] h-screen">
    <h3 class="text-center">LOGIN TO YOUR ACCOUNT</h3>
    <form class="space-y-5 w-full max-w-md bg-white rounded px-8 pt-6 pb-8 mb-4 text-sm" on:submit={handleSubmit}>
        <input bind:value={login} type="login" id="login" placeholder="Email Address or Username" class="border-[1px] border-gray-400 p-1 min-w-[400px]" />
        <input bind:value={password} type="password" id="password" placeholder="Password" class="border-[1px] border-gray-400 p-1 min-w-[400px]" />
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" >
            Sign In
        </button>
    </form>
</div>
<!--
<script>
    let login = 'Hoar';
    let password = 'Hoar123';
  
    /**
     * @param {{ preventDefault: () => void; }} event
     */
    async function handleSubmit(event) {
      event.preventDefault();
  
      const formData = {
        login: login,
        password: password,
      };
  
      const response = await fetch('http://127.0.0.1:8000/api/user/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
  
      const data = await response.json();
      console.log(data);
    }
  </script>
-->

<!--
<div class="flex justify-center items-center h-screen">
    <form  class="w-full max-w-md bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" on:submit={handleSubmit}>
        <h1 class="text-xl font-bold mb-6 text-center">Register Form</h1>
        <div class="mb-4">
            <label class="block text-gray-700 font-bold mb-2" for="username">
                Username or Email
            </label>
            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" type="text" id="username" bind:value={login} />
        </div>
        <div class="mb-6">
            <label class="block text-gray-700 font-bold mb-2" for="password">
                Password
            </label>
            <input type="password" id="password" bind:value={password} />
        </div>
        <div class="flex items-center justify-between">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" >
                Sign In
            </button>
        </div>
    </form>
</div>
-->

// packages/client/blog-front/debug/login/page.tsx
'use client';

import Image from 'next/image'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Login',
    description: 'Login to your account',
  }
  
export default function Page() {
  let login = "Doggy"
  let password = "Doggy123!"
    let handleSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault();
    try {
      let res = await fetch("http://localhost:8000/api/user/login", {
        method: "POST",
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
          "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept",
          'Origin': 'http://localhost:3000/',
        },
        body: JSON.stringify({
          login: login,
          password: password
        }),
      });
      let resJson = await res.json();
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <>
    <div className='text-7xl mb-2 text-center'>Login</div>
    <form className="flex flex-col bg-[#572536] space-y-3 p-3 rounded" onSubmit={handleSubmit}>
        <input className='p-1 bg-[#421525]' placeholder='Email or Username'></input>
        <input className='p-1 bg-[#421525]' type='password' placeholder='Password'></input>
        <button>Login</button>
    </form>
    </>
  )
}
