// packages/client/blog-front/src/routes/register/+page.svelte

<script>
  let username = 'Testy';
  let email = 'Testy@gmail.com';
  let password = 'Doggy123!';
  let result = ''

  /**
   * @param {{ preventDefault: () => void; }} event
   */
  async function handleSubmit(event) {
    event.preventDefault();

    const formData = {
      username: username,
      email: email,
      password: password,
    };

    const response = await fetch('http://127.0.0.1:8000/api/user/create', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(formData),
    });

   // const data = await response.json();
   // console.log(data);
  }
</script>

<div class="flex flex-col justify-center items-center bg-[#fff] h-screen">
  <h3 class="text-center">LOGIN TO YOUR ACCOUNT</h3>
  <form class="space-y-5 w-full max-w-md bg-white rounded px-8 pt-6 pb-8 mb-4 text-sm" on:submit={handleSubmit}>
      <input bind:value={username} type="username" id="username" placeholder="Username" class="border-[1px] border-gray-400 p-1 min-w-[400px]" />
      <input bind:value={email} type="email" id="email" placeholder="Email Address" class="border-[1px] border-gray-400 p-1 min-w-[400px]" />
      <input bind:value={password} type="password" id="password" placeholder="Password" class="border-[1px] border-gray-400 p-1 min-w-[400px]" />
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" >
          Register
      </button>
  </form>
</div>

<!--
<script>
    let username = 'doggy';c
    let email = 'hello@gmail.com';
    let password = 'Doggy123!das';
  
    /**
     * @param {{ preventDefault: () => void; }} event
     */
    async function handleSubmit(event) {
      event.preventDefault();
  
      const formData = {
        username: username,
        email: email,
        password: password,
      };
  
      const response = await fetch('http://127.0.0.1:8000/api/user/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
  
      const data = await response.json();
      console.log(data);
    }
  </script>

<div class="flex justify-center items-center h-screen">
    <form  class="w-full max-w-md bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" on:submit={handleSubmit}>
        <h1 class="text-xl font-bold mb-6 text-center">Register Form</h1>
        <div class="mb-4">
            <label class="block text-gray-700 font-bold mb-2" for="username">
                Username or Email
            </label>
            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" type="text" id="username" bind:value={username} />
        </div>
        <div class="mb-6">
            <label class="block text-gray-700 font-bold mb-2" for="email">
                Email
            </label>
            <input type="email" id="email" bind:value={email} />
            <label class="block text-gray-700 font-bold mb-2" for="password">
                Password
            </label>
            <input type="password" id="password" bind:value={password} />
        </div>
        <div class="flex items-center justify-between">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" >
                Sign In
            </button>
        </div>
    </form>
</div>
-->

// packages/client/blog-front/app/register/page.tsx
'use client';

import { Metadata } from 'next'
import { useState } from 'react';
import { useRouter } from 'next/router';

export default function Page() {

   let url = "http://localhost:8000/api/user/create"
   const [formData, setFormData] = useState({
      username: '',
      email: '',
      password: ''
   })

    const handleSubmit = async (event: any) => {
      event.preventDefault();
      let res = await fetch(url, {
          method: "POST",
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(formData),
        });
        let data = await res.json();
        if (res.status === 200) {
          console.log("Success: " + data["message"])
          window.location.href = "/";
        } else {
          console.log("Failed: " + data["message"])
        }
    };

  
  
  return (
    <>
    <div className='text-7xl mb-2 text-center'>Register</div>
    <form className="flex flex-col bg-[#572536] space-y-3 p-3 rounded" onSubmit={handleSubmit}>
        <input className='p-1 bg-[#421525]' type='username' value={formData.username} onChange={(e) => setFormData({ ...formData, username: e.target.value })}></input>
        <input className='p-1 bg-[#421525]' type='email' value={formData.email} onChange={(e) => setFormData({ ...formData, email: e.target.value })}></input>
        <input className='p-1 bg-[#421525]' type='password' value={formData.password} onChange={(e) => setFormData({ ...formData, password: e.target.value })}></input>
        <button>Register</button>
    </form>
    </>
  )
}

/*
export const metadata: Metadata = {
    title: 'Register',
    description: 'Register your account',
}
  
export default function Page() {

  const [formData, setFormData] = useState({
    username: '',
    email: '',
    password: ''
  })
 
  };
    
  return (
    <>
    <div className='text-7xl mb-2 text-center'>Register</div>
    <form className="flex flex-col bg-[#572536] space-y-3 p-3 rounded" onSubmit={handleSubmit}>
        <input className='p-1 bg-[#421525]' type='username' value={username} onChange={(e) => setUsername(e.target.value)}></input>
        <input className='p-1 bg-[#421525]' type='email' value={email} onChange={(e) => setEmail(e.target.value)}></input>
        <input className='p-1 bg-[#421525]' type='password' value={password} onChange={(e) => setPassword(e.target.value)}></input>
        <button>Register</button>
        <div className="message">{message ? <p>{message}</p> : null}</div>
    </form>
    </>
  )
}
*/

 /*()
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [message, setMessage] = useState("");
  const router = useRouter();

  let handleSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault();
    try {
      let res = await fetch("http://localhost:8000/api/user/create", {
        method: "POST",
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          username: username,
          email: email,
          password: password
        }),
      });
      let resJson = await res.json();
      router.push('/login');

      if (res.status === 200) {
        setUsername("");
        setEmail("");
        setPassword("");
        setMessage("User created successfully");
      } else {
        setMessage(resJson["message"]);
      }
    } catch (err) {
      console.log(err);
    }
    */
