// packages/client/blog-front/debug/create-post/page.tsx
import Image from 'next/image'
import { Metadata } from 'next'
import { useState } from 'react';

export const metadata: Metadata = {
    title: 'Create Post',
    description: 'Create a post on the blog',
  }
  
export default function Page() {
  
  return (
    <>
    <div className='text-7xl mb-2 text-center'>Create a thread</div>
    <form className="flex flex-col bg-[#572536] space-y-3 p-3 rounded">
        <input className='p-1 bg-[#421525]' placeholder='Title'></input>
        <textarea className='p-1 bg-[#421525]' placeholder='INPUT TEXT'></textarea>
        <button>Post</button>
    </form>
    </>
  )
}

// packages/client/blog-front/src/routes/create_post/+page.svelte
<!DOCTYPE html>

<div class="flex justify-center items-center h-screen">
    <form class="w-full max-w-md bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <h1 class="text-xl font-bold mb-6 text-center">Login Form</h1>
        <div class="mb-4">
            <label class="block text-gray-700 font-bold mb-2" for="post_title">
                Title
            </label>
            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="post_title" type="text" placeholder="Title">
        </div>
        <div class="mb-6">
            <label class="block text-gray-700 font-bold mb-2" for="post_body">
                Body
            </label>
            <textarea
            class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            id="body" name="body" rows="5" placeholder="Enter thread body"></textarea>
        </div>
        <div class="flex items-center justify-between">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="button">
                Create Post
            </button>
        </div>
    </form>
</div>
