// packages/client/blog-front/app/auth/login/page.tsx
'use client';

import { Metadata } from 'next'
import { useState } from 'react';
import { useRouter } from 'next/router';

export default function Page() {

  let url = "http://localhost:8000/api/user/login"
  const [formData, setFormData] = useState({
    login: '',
    password: '',
  })

  const handleSubmit = async (event: any) => {
    event.preventDefault();
    let res = await fetch(url, {
      method: "POST",
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(formData),
    });
    let data = await res.json();
    if (res.status === 200) {
      console.log("Success: " + data["message"])
      window.location.href = "/";
    } else {
      console.log("Failed: " + data["message"])
    }
  };

  return (
    <>
    <div className='flex h-screen'>
      <div className='lg:flex md:hidden hidden bg-[#4E192B] w-3/6'>
          <div className='flex flex-row font-semibold m-3 text-2xl space-x-2'>
            <span>BLOG</span>
            <span className='text-sm'>"Write something great."</span>
          </div>
      </div>
      <div className='flex justify-center items-center bg-[#fff] w-screen text-black'>
          <div className='flex flex-col space-y-5 min-w-[400px] min-h-[400px] '>
            <h2 className='text-2xl'>Login</h2>
            <form className="flex flex-col space-y-5 rounded w-[300px]" onSubmit={handleSubmit}>
              <div className='flex flex-col space-y-2'>
                  <label className='font-bold text-sm'>Username or Email</label>
                  <input className='border-2 p-1.5 text-sm' placeholder='Username or Email' value={formData.login} onChange={(e) => setFormData({ ...formData, login: e.target.value })}></input>
              </div>
              <div className='flex flex-col space-y-2'>
                  <label className='font-bold text-sm'>Password</label>
                  <input className='border-2 p-1.5 text-sm' type='password' placeholder='Password' value={formData.password} onChange={(e) => setFormData({ ...formData, password: e.target.value })}></input>
              </div>
              <div className='flex flex-col space-y-2'>
                  <button className='bg-[#4E192B] rounded text-white p-2 hover:bg-[#603040]' placeholder='Password'>Login</button>
                  <span className='text-sm'>Don't have an account? <a href="/auth/register" className='text-[#234E52] hover:text-[#A29E9D]'>Register</a></span>
              </div>
            </form>
          </div>
      </div>
    </div>
    </>
  )
}

// packages/client/blog-front/src/routes/login/+page.svelte

<script>
    let login = 'Hoar';
    let password = 'Hoar123';
  
    /**
     * @param {{ preventDefault: () => void; }} event
     */
    async function handleSubmit(event) {
      event.preventDefault();
  
      const formData = {
        login: login,
        password: password,
      };
  
      const response = await fetch('http://127.0.0.1:8000/api/user/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
  
      const data = await response.json();
      console.log(data);
    }
  </script>


<div class="flex flex-col justify-center items-center bg-[#fff] h-screen">
    <h3 class="text-center">LOGIN TO YOUR ACCOUNT</h3>
    <form class="space-y-5 w-full max-w-md bg-white rounded px-8 pt-6 pb-8 mb-4 text-sm" on:submit={handleSubmit}>
        <input bind:value={login} type="login" id="login" placeholder="Email Address or Username" class="border-[1px] border-gray-400 p-1 min-w-[400px]" />
        <input bind:value={password} type="password" id="password" placeholder="Password" class="border-[1px] border-gray-400 p-1 min-w-[400px]" />
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" >
            Sign In
        </button>
    </form>
</div>
<!--
<script>
    let login = 'Hoar';
    let password = 'Hoar123';
  
    /**
     * @param {{ preventDefault: () => void; }} event
     */
    async function handleSubmit(event) {
      event.preventDefault();
  
      const formData = {
        login: login,
        password: password,
      };
  
      const response = await fetch('http://127.0.0.1:8000/api/user/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      });
  
      const data = await response.json();
      console.log(data);
    }
  </script>
-->

<!--
<div class="flex justify-center items-center h-screen">
    <form  class="w-full max-w-md bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" on:submit={handleSubmit}>
        <h1 class="text-xl font-bold mb-6 text-center">Register Form</h1>
        <div class="mb-4">
            <label class="block text-gray-700 font-bold mb-2" for="username">
                Username or Email
            </label>
            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" type="text" id="username" bind:value={login} />
        </div>
        <div class="mb-6">
            <label class="block text-gray-700 font-bold mb-2" for="password">
                Password
            </label>
            <input type="password" id="password" bind:value={password} />
        </div>
        <div class="flex items-center justify-between">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" >
                Sign In
            </button>
        </div>
    </form>
</div>
-->
